services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: pern_db
      POSTGRES_PASSWORD: root
    volumes:
      - ./database/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"

  server:
    container_name: server
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database
    command: npm run dev

  client:
    container_name: client
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
    command: npm run dev -- --host 0.0.0.0
