name: Test Suite

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: me
          POSTGRES_PASSWORD: password
          POSTGRES_DB: client
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (server)
        run: |
          cd server
          npm ci

      - name: Install dependencies (client)
        run: |
          cd client
          npm ci

      - name: Run server tests
        run: |
          cd server
          npm test
        env:
          NODE_ENV: test
          POSTGRES_USER: me
          POSTGRES_PASSWORD: password
          POSTGRES_DB: client
          POSTGRES_HOST: localhost

      - name: Run client tests
        run: |
          cd client
          npm test
        env:
          CI: true
